"""esquema inicial: 9 tablas con relaciones de Bloque 1

Revision ID: f1d4959577f8
Revises: 
Create Date: 2026-06-21 17:06:47.358947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d4959577f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('mesas',
    sa.Column('id_mesa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('libre', 'ocupada', 'por_limpiar', name='estadomesa'), nullable=True),
    sa.Column('codigo_qr', sa.String(length=255), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id_mesa'),
    sa.UniqueConstraint('codigo_qr'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'mesero', name='rolusuario'), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadousuario'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('llamar_mesero', 'pedir_cuenta', name='tipoasistencia'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'atendido', name='estadoasistencia'), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id_mesa'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_index(op.f('ix_asistencias_id_mesa'), 'asistencias', ['id_mesa'], unique=False)
    op.create_table('comensales',
    sa.Column('id_comensal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('estado_sesion', sa.Enum('activa', 'inactiva', name='estadosesion'), nullable=True),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id_mesa'], ),
    sa.PrimaryKeyConstraint('id_comensal')
    )
    op.create_index(op.f('ix_comensales_id_mesa'), 'comensales', ['id_mesa'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_preparacion', 'servido', 'pagado', 'cancelado', name='estadopedido'), nullable=True),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('id_comensal', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comensal'], ['comensales.id_comensal'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('detalles_pedido',
    sa.Column('id_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('propina', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'tarjeta', 'yape', 'plin', name='metodopago'), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('detalles_pedido')
    op.drop_table('pedidos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_comensales_id_mesa'), table_name='comensales')
    op.drop_table('comensales')
    op.drop_index(op.f('ix_asistencias_id_mesa'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_table('usuarios')
    op.drop_table('mesas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
